/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author alexandrezamberlan
 */
public class JFrame_principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_principal
     */
    public JFrame_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_file = new javax.swing.JMenu();
        jMenuItem_abrirArquivo = new javax.swing.JMenuItem();
        jMenuItem_selecionarMetodo = new javax.swing.JMenuItem();
        jMenuItem_mostrarHistorico = new javax.swing.JMenuItem();
        jMenu_about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_file.setText("Arquivo");

        jMenuItem_abrirArquivo.setText("Abrir arquivo");
        jMenu_file.add(jMenuItem_abrirArquivo);

        jMenuItem_selecionarMetodo.setText("Selecionar método");
        jMenu_file.add(jMenuItem_selecionarMetodo);

        jMenuItem_mostrarHistorico.setText("Histórico de testes");
        jMenu_file.add(jMenuItem_mostrarHistorico);

        jMenuBar1.add(jMenu_file);

        jMenu_about.setText("Sobre");
        jMenu_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_aboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_aboutActionPerformed
        // TODO add your handling code here:
        StringBuffer texto = new StringBuffer();
        //String - limite de caracteres e de funções de manipulação
        //StringBuffer - possui funções de manipulação de string avançada
        //StringBuilder - possui funções de manipulação de string avançada, com capacidade de armazenamento muito grande
        
        texto.append("Sistema construído na disciplina de Pesquisa e Ordenação\n");
        texto.append("Alunos: Gabriel, Augusto, Zeni, Regis, Lucas Thiago, Meani e João\n");
        
        
        JOptionPane.showMessageDialog(this, texto.toString());
    }//GEN-LAST:event_jMenu_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_abrirArquivo;
    private javax.swing.JMenuItem jMenuItem_mostrarHistorico;
    private javax.swing.JMenuItem jMenuItem_selecionarMetodo;
    private javax.swing.JMenu jMenu_about;
    private javax.swing.JMenu jMenu_file;
    // End of variables declaration//GEN-END:variables
}
