
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action MenuAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview_texto;

	private global::Gtk.Button button_arquivo;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview_pesquisar;

	private global::Gtk.Label label2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview_ocorrencias;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.MenuAction = new global::Gtk.Action("MenuAction", global::Mono.Unix.Catalog.GetString("Menu"), null, null);
		this.MenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menu");
		w1.Add(this.MenuAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 335;
		this.GtkScrolledWindow.HeightRequest = 221;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview_texto = new global::Gtk.TextView();
		this.textview_texto.CanFocus = true;
		this.textview_texto.Name = "textview_texto";
		this.textview_texto.Justification = ((global::Gtk.Justification)(3));
		this.textview_texto.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add(this.textview_texto);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w3.X = 25;
		w3.Y = 111;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_arquivo = new global::Gtk.Button();
		this.button_arquivo.CanFocus = true;
		this.button_arquivo.Name = "button_arquivo";
		this.button_arquivo.UseUnderline = true;
		this.button_arquivo.Label = global::Mono.Unix.Catalog.GetString("Arquivo");
		this.fixed1.Add(this.button_arquivo);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_arquivo]));
		w4.X = 26;
		w4.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Pesquisar");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w5.X = 138;
		w5.Y = 32;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.WidthRequest = 160;
		this.GtkScrolledWindow1.HeightRequest = 20;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview_pesquisar = new global::Gtk.TextView();
		this.textview_pesquisar.CanFocus = true;
		this.textview_pesquisar.Name = "textview_pesquisar";
		this.GtkScrolledWindow1.Add(this.textview_pesquisar);
		this.fixed1.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
		w7.X = 198;
		w7.Y = 27;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Ocorrências");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w8.X = 123;
		w8.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.WidthRequest = 160;
		this.GtkScrolledWindow2.HeightRequest = 20;
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview_ocorrencias = new global::Gtk.TextView();
		this.textview_ocorrencias.CanFocus = true;
		this.textview_ocorrencias.Name = "textview_ocorrencias";
		this.textview_ocorrencias.Editable = false;
		this.GtkScrolledWindow2.Add(this.textview_ocorrencias);
		this.fixed1.Add(this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow2]));
		w10.X = 198;
		w10.Y = 61;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 368;
		this.DefaultHeight = 341;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button_arquivo.Clicked += new global::System.EventHandler(this.abrirArquivo);
		this.textview_pesquisar.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.pesquisarTexto);
	}
}
